document.addEventListener("DOMContentLoaded", function() {
  const landscapePopup = document.getElementById("landscape-popup");

  // Function to show or hide the landscape popup
  function toggleLandscapePopup() {
    if (window.innerWidth < window.innerHeight) {
      landscapePopup.style.display = "block";
    } else {
      landscapePopup.style.display = "none";
    }
  }

  // Initial check
  toggleLandscapePopup();

  // Check orientation on window resize
  window.addEventListener("resize", toggleLandscapePopup);

  // Add event listener for Enter key press in the symptoms input
  document.getElementById('symptoms').addEventListener('keypress', function(event) {
    if (event.key === 'Enter') {
      suggestMedicine();
    }
  });
});

function suggestMedicine() {
  // Get the input value of symptoms and convert to lowercase
  const symptomsInput = document.getElementById('symptoms').value.toLowerCase();
  // Split the symptoms by comma and trim whitespaces
  const symptoms = symptomsInput.split(',').map(symptom => symptom.trim());

  // Check if symptoms are provided
  if (!symptomsInput) {
    document.getElementById('medicineSuggestion').textContent = "Please provide symptoms.";
    return; // Exit the function early if no symptoms are provided
  }

  // Array to store suggested medicines
  const suggestedMedicines = [];
  
  // Iterate through the symptoms and suggest corresponding medicines
  symptoms.forEach(symptom => {
    if (medicineMapping.hasOwnProperty(symptom)) {
      suggestedMedicines.push(medicineMapping[symptom]);
    }
  });

  // Display the suggested medicines or indicate no information available
  const suggestionElement = document.getElementById('medicineSuggestion');
  if (suggestedMedicines.length > 0) {
    suggestionElement.textContent = "Suggested cures: " + suggestedMedicines.join(', ');
  } else {
    suggestionElement.textContent = "No information available for the given symptoms. It may be available in the future";
  }
}

  
  // Define a dictionary mapping symptoms to medicines with lowercase keys
  const medicineMapping = {
    'headache': 'Aspirin',
    'fever': 'Paracetamol',
    'cough': 'Cough Syrup',
    'stomachache': 'Antacid, Dicyclomine',
    'stomach ache': 'Antacid, Dicyclomine',
    'sore throat': 'Lozenges, Drink Saline Water, Ibuprofen',
    'chest pain' : 'Lozenges, Drink Carbonated Water',
    'pain' : 'Ibprofen, Apply Pain Reliever',
    'eye redness' :  'Wash your eyes with running cold water, Eye Drops',
    'cold' : 'Drink Warm Water, Consumption of Chicken Clear Soup',
    'fatigue' : 'Drink Glucose, Energy Drinks, Saline Water/ ORS',
    'stress' : 'Listen to Calm/Mind-Soothing Music, Meditate, Consult a Psycologist',
    'fatigue' : 'Drink glucose, energy drinks, saline water/ ORS',
    'stress' : 'Listen to calm music, meditate, consult a psychologist',
    'psoriasis' : 'Moisturizer, consult a doctor',
    'sore eyes' : 'Eye drops, artificial tears',
    'heartburn' : 'Avoid spicy food',
    'cut' : 'Antiseptic, wash with cold water',
    'bleeding' : 'Antiseptic, wash with cold water',
    'burn' : 'Wash with cold water, keep an ice pack on the burnt area, aloe vera',
    'insomnia' : 'Avoid caffeine, avoid watching mobile phone or TV before sleeping',
    'rash': 'Apply calamine lotion, avoid scratching',
    'diarrhea': 'Drink plenty of fluids, eat bland foods',
    'typhoid' : 'Ciprofloxacin, Chloromycetin ',
  'constipation': 'Increase fiber intake, drink plenty of water',
  'indigestion': 'Take antacids, avoid spicy and fatty foods',
  'anxiety': 'Practice deep breathing, exercise regularly',
  'depression': 'Seek therapy, talk to a counselor',
  'allergies': 'Take antihistamines, avoid allergens',
  'migraine': 'Rest in a quiet, dark room, use cold compress',
  'toothache': 'Rinse with warm salt water, apply clove oil',
  'earache': 'Apply warm compress, avoid inserting objects into the ear',
  'sprain': 'Rest, ice, compress, elevate (RICE)',
  'strain': 'Rest, apply ice packs, use compression bandage',
  'bruise': 'Apply cold compress, elevate the affected area',
  'sunburn': 'Apply cool compresses, moisturize with aloe vera',
  'poison ivy': 'Wash affected area with soap and water, apply calamine lotion',
  'hives': 'Take antihistamines, avoid triggers',
  'sore muscles': 'Rest, apply heat or cold therapy',
  'athlete\'s foot': 'Keep feet clean and dry, apply antifungal cream',
  'ringworm': 'Apply antifungal cream, keep area clean and dry',
  'acne': 'Wash face with gentle cleanser, use topical treatments',
  'eczema': 'Use moisturizers, avoid triggers like harsh soaps',
  'sunburn': 'Apply cool compresses, moisturize with aloe vera',
  'chapped lips': 'Use lip balm, stay hydrated',
  'stomach flu': 'Stay hydrated, rest, eat bland foods',
  'motion sickness': 'Sit in the front seat of a car, focus on the horizon',
  'jet lag': 'Adjust sleep schedule gradually, stay hydrated',
  'hangover': 'Drink water, eat a balanced meal, get rest',
  'food poisoning': 'Stay hydrated, rest, avoid solid foods initially',
  'heat exhaustion': 'Move to a cool place, drink water, rest',
  'heat stroke': 'Seek medical help immediately, move to a cool place',
  'hypertension': 'Eat a balanced diet, exercise regularly, manage stress',
  'hypotension': 'Drink more fluids, avoid sudden position changes',
  'diabetes': 'Monitor blood sugar levels, eat a balanced diet',
  'asthma': 'Use inhaler as prescribed, avoid triggers',
  'bronchitis': 'Stay hydrated, rest, use humidifier',
  'pneumonia': 'Take prescribed antibiotics, get plenty of rest',
  'sinusitis': 'Use saline nasal spray, apply warm compress',
  'ear infection': 'Use prescribed ear drops, apply warm compress',
  'pink eye': 'Use prescribed eye drops, avoid touching eyes',
  'gout': 'Avoid high-purine foods, stay hydrated',
  'menstrual cramps': 'Apply heat, take pain relievers',
  'menopause symptoms': 'Stay active, eat a balanced diet',
  'premenstrual syndrome (PMS)': 'Exercise regularly, eat healthy',
  'urinary tract infection (UTI)': 'Drink plenty of water, take antibiotics',
  'kidney stones': 'Stay hydrated, take pain relievers',
  'meningitis': 'Seek medical help immediately, get plenty of rest',
  'rabies': 'Seek medical help immediately, get vaccinated',
  'malaria': 'Take prescribed antimalarial drugs, use mosquito nets',
  'tuberculosis': 'Take prescribed antibiotics, get plenty of rest',
  'cholera': 'Drink oral rehydration solution (ORS), seek medical help',
  'dengue fever': 'Stay hydrated, rest, use mosquito nets',
  'yellow fever': 'Get vaccinated, avoid mosquito bites',
  'ebola': 'Seek medical help immediately, follow preventive measures',
  'zika virus': 'Avoid mosquito bites, practice safe sex',
  'chickenpox': 'Use calamine lotion, take antihistamines',
  'measles': 'Get vaccinated, rest, take pain relievers',
  'mumps': 'Rest, use cold compresses, take pain relievers',
  'rubella': 'Get vaccinated, rest, take pain relievers',
  'polio': 'Get vaccinated, practice good hygiene',
  'hepatitis': 'Get vaccinated, practice good hygiene',
  'HIV/AIDS': 'Take antiretroviral drugs, practice safe sex',
  'influenza': 'Get vaccinated, rest, take antiviral drugs',
  'common cold': 'Stay hydrated, get plenty of rest',
  'norovirus': 'Stay hydrated, rest, practice good hygiene',
  'Lyme disease': 'Take prescribed antibiotics, use insect repellent',
  'pneumococcal disease': 'Get vaccinated, practice good hygiene',
  'whooping cough': 'Get vaccinated, take antibiotics',
  'tuberculosis': 'Take prescribed antibiotics, get plenty of rest',
  'streptococcal infection': 'Take prescribed antibiotics, get plenty of rest',
  'salmonella infection': 'Stay hydrated, rest, eat bland foods',
  'shingles': 'Take antiviral drugs, use pain relievers, apply cool compresses',
  'sepsis': 'Seek medical help immediately, get antibiotic treatment',
  'severe acute respiratory syndrome (SARS)': 'Seek medical help immediately, practice good hygiene',
  'malaria': 'Take prescribed antimalarial drugs, use mosquito nets',
  'west Nile virus': 'Stay indoors during peak mosquito activity, use mosquito repellent',
  'avian influenza': 'Avoid contact with infected birds, get vaccinated',
  'swine flu': 'Get vaccinated, practice good hygiene',
  'Middle East respiratory syndrome (MERS)': 'Seek medical help immediately, practice good hygiene',
  'coronavirus disease (COVID-19)': 'Wear masks, practice social distancing, get vaccinated',
  'rotavirus': 'Stay hydrated, practice good hygiene',
  'Ebola virus disease': 'Seek medical help immediately, practice good hygiene',
  'Marburg virus disease': 'Seek medical help immediately, practice good hygiene',
  'severe acute respiratory syndrome (SARS)': 'Seek medical help immediately, practice good hygiene',
  'cholera': 'Drink oral rehydration solution (ORS), seek medical help',
  'liver disease': 'Follow prescribed treatment, avoid alcohol, maintain a healthy diet',
  'kidney disease': 'Follow prescribed treatment, manage blood pressure and blood sugar levels',
  'heart disease': 'Follow prescribed treatment, maintain a healthy diet, exercise regularly',
  'stroke': 'Seek immediate medical help, follow prescribed treatment, attend rehabilitation',
  'asthma': 'Use inhaler as prescribed, avoid triggers',
  'chronic obstructive pulmonary disease (COPD)': 'Use prescribed medications, avoid smoke and pollutants',
  'diabetes': 'Monitor blood sugar levels, follow prescribed treatment, maintain a healthy lifestyle',
  'cancer': 'Undergo prescribed treatments (chemotherapy, radiation therapy, surgery), manage symptoms',
  'Alzheimer\'s disease': 'Follow prescribed treatment, maintain a supportive environment, seek caregiver support',
  'Parkinson\'s disease': 'Take prescribed medications, attend physical therapy, maintain a healthy lifestyle',
  'arthritis': 'Stay active, use pain relievers, attend physical therapy',
  'osteoporosis': 'Take prescribed medications, consume calcium and vitamin D, engage in weight-bearing exercise',
  'fibromyalgia': 'Get regular exercise, manage stress, get enough sleep',
  'multiple sclerosis': 'Take prescribed medications, attend physical therapy, maintain a healthy lifestyle',
  'Crohn\'s disease': 'Follow prescribed treatment, maintain a healthy diet, manage stress',
  'ulcerative colitis': 'Follow prescribed treatment, maintain a healthy diet, manage stress',
  'irritable bowel syndrome (IBS)': 'Identify triggers, manage stress, follow a low-FODMAP diet',
  'celiac disease': 'Follow a gluten-free diet, manage symptoms with medication if needed',
  'hypothyroidism': 'Take thyroid hormone replacement medication, maintain a healthy diet',
  'hyperthyroidism': 'Take prescribed medications (antithyroid drugs, beta blockers), manage symptoms',
  'anemia': 'Take iron supplements, eat foods rich in iron and vitamin C, manage underlying cause',
  'vitamin deficiency': 'Take vitamin supplements, eat a balanced diet, manage underlying cause',
  'hypertension': 'Follow a low-sodium diet, exercise regularly, manage stress',
  'hypotension': 'Increase fluid and salt intake, wear compression stockings, avoid prolonged standing',
  'high cholesterol': 'Follow a low-fat diet, exercise regularly, take prescribed medications',
  'diarrhea': 'Stay hydrated, eat bland foods, take anti-diarrheal medications if needed',
  'constipation': 'Eat foods high in fiber, drink plenty of water, exercise regularly',
  'gastroesophageal reflux disease (GERD)': 'Avoid trigger foods, eat smaller meals, elevate the head of the bed',
  'peptic ulcer disease': 'Avoid trigger foods, take prescribed medications (antacids, antibiotics, proton pump inhibitors)',
  'gallstones': 'Eat a low-fat diet, avoid rapid weight loss, manage symptoms with medication if needed',
  'liver cirrhosis': 'Avoid alcohol, follow a low-sodium diet, take prescribed medications',
  'hepatitis': 'Get vaccinated (if applicable), avoid alcohol and drugs, follow prescribed treatment',
  'pancreatitis': 'Avoid alcohol, follow a low-fat diet, manage symptoms with pain relievers and enzyme supplements',
  'irritable bowel syndrome (IBS)': 'Identify trigger foods, manage stress, follow a low-FODMAP diet',
  'diverticulitis': 'Eat a high-fiber diet, avoid seeds and nuts, take prescribed antibiotics if needed',
  'hemorrhoids': 'Eat high-fiber foods, drink plenty of water, use over-the-counter treatments for pain and itching',
  'celiac disease': 'Follow a strict gluten-free diet, manage symptoms with medication if needed',
  'food allergies': 'Avoid trigger foods, carry an epinephrine auto-injector (if applicable), seek medical help for severe reactions',
  'lactose intolerance': 'Avoid dairy products, use lactase supplements if needed, consume lactose-free dairy alternatives',
  'sleep apnea': 'Use a CPAP machine, lose weight if needed, avoid alcohol and sedatives before bedtime',
  'insomnia': 'Establish a bedtime routine, limit caffeine and screen time before bed, practice relaxation techniques',
  'narcolepsy': 'Take prescribed medications (stimulants, antidepressants), take short naps during the day, maintain a regular sleep schedule',
  'restless legs syndrome': 'Take prescribed medications (dopamine agonists, opioids), practice good sleep hygiene, exercise regularly',
  'migraine': 'Take prescribed medications (triptans, NSAIDs), identify and avoid triggers, practice relaxation techniques',
  'tension headache': 'Take over-the-counter pain relievers, practice relaxation techniques, manage stress',
  'cluster headache': 'Take prescribed medications (triptans, oxygen therapy), avoid triggers, maintain a regular sleep schedule',
  'sinus headache': 'Use nasal decongestants, apply warm compresses to the face, use saline nasal irrigation',
  'TMJ disorder': 'Apply cold packs to the jaw, avoid hard or chewy foods, practice relaxation techniques',
  'trigeminal neuralgia': 'Take prescribed medications (anticonvulsants, muscle relaxants), avoid triggers like cold air and wind',
  'fibromyalgia': 'Get regular exercise, practice relaxation techniques, maintain a regular sleep schedule',
  'myofascial pain syndrome': 'Apply heat or cold packs to affected areas, practice relaxation techniques, undergo physical therapy',
  'temporomandibular joint dysfunction (TMD)': 'Apply moist heat or cold packs to the jaw, avoid hard or chewy foods, practice relaxation techniques',
  'plantar fasciitis': 'Rest the foot, apply ice, perform stretching exercises, wear supportive shoes',
  'Achilles tendinitis': 'Rest the foot, apply ice, perform stretching exercises, wear supportive shoes',
  'shin splints': 'Rest the leg, apply ice, perform stretching exercises, wear supportive shoes',
  'patellar tendinitis': 'Rest the knee, apply ice, perform stretching exercises, wear a knee brace',
  'tennis elbow': 'Rest the arm, apply ice, perform stretching and strengthening exercises',
  'golfer\'s elbow': 'Rest the arm, apply ice, perform stretching and strengthening exercises',
  'carpal tunnel syndrome': 'Rest the wrist, apply ice, wear a wrist splint, perform stretching exercises',
  'sciatica': 'Apply hot or cold packs, perform stretching exercises, take over-the-counter pain relievers',
  'herniated disc': 'Rest, apply ice or heat, take over-the-counter pain relievers, perform gentle exercises',
  'whiplash': 'Apply ice or heat, take over-the-counter pain relievers, perform gentle neck exercises',
  'rotator cuff injury': 'Rest the shoulder, apply ice or heat, perform stretching and strengthening exercises',
  'frozen shoulder': 'Apply ice or heat, perform stretching and strengthening exercises, seek physical therapy',
  'osteoarthritis': 'Exercise regularly, apply heat or cold packs, take over-the-counter pain relievers',
  'rheumatoid arthritis': 'Take prescribed medications (DMARDs, biologics), exercise regularly, apply heat or cold packs',
  'gout': 'Avoid trigger foods (high-purine foods), take prescribed medications (NSAIDs, colchicine)',
  'ankylosing spondylitis': 'Exercise regularly, take prescribed medications (NSAIDs, biologics), practice good posture',
  'osteoporosis': 'Take prescribed medications (bisphosphonates, hormone therapy), consume calcium and vitamin D, perform weight-bearing exercises',
  'fibromyalgia': 'Get regular exercise, practice relaxation techniques, maintain a regular sleep schedule',
  'chronic fatigue syndrome': 'Practice pacing and activity management, get restorative sleep, seek support from healthcare professionals',
  'endometriosis': 'Take prescribed medications (pain relievers, hormonal therapies), practice heat therapy, seek surgical intervention if needed',
  'polycystic ovary syndrome (PCOS)': 'Maintain a healthy diet, exercise regularly, manage symptoms with hormonal therapies if needed',
  'pelvic inflammatory disease (PID)': 'Take prescribed antibiotics, rest, avoid sexual activity until treatment is completed',
  'premenstrual syndrome (PMS)': 'Exercise regularly, eat a balanced diet, practice stress management techniques',
  'vaginal yeast infection': 'Take antifungal medications, practice good hygiene, avoid irritants like scented products',
  'bacterial vaginosis': 'Take prescribed antibiotics, practice good hygiene, avoid irritants like scented products',
  'urinary tract infection (UTI)': 'Take prescribed antibiotics, drink plenty of water, avoid irritants like caffeine and alcohol',
  'cystitis': 'Take prescribed antibiotics, drink plenty of water, apply heat to the abdomen',
  'interstitial cystitis': 'Follow dietary restrictions (avoiding acidic foods, caffeine, alcohol), take prescribed medications (pain relievers, bladder relaxants)',
  'vulvodynia': 'Apply topical treatments (lidocaine, estrogen cream), practice pelvic floor physical therapy, manage stress',
  'dysmenorrhea': 'Take pain relievers (NSAIDs, hormonal contraceptives), apply heat to the abdomen, practice relaxation techniques',
  'pelvic floor dysfunction': 'Practice pelvic floor physical therapy, perform Kegel exercises, manage stress',
  'vaginismus': 'Practice relaxation techniques, undergo pelvic floor physical therapy, seek counseling or sex therapy',
  'postpartum depression': 'Seek support from healthcare professionals, join support groups, practice self-care activities',
  'postpartum psychosis': 'Seek emergency medical help immediately, hospitalization may be necessary, follow prescribed treatment',
  'mastitis': 'Continue breastfeeding or pumping, take prescribed antibiotics, apply warm compresses to the affected breast',
  'low milk supply': 'Breastfeed frequently or pump regularly, ensure proper latch and positioning, manage stress',
  'engorgement': 'Breastfeed frequently or pump regularly, apply cold compresses between feedings, manage discomfort with pain relievers if needed',
  'nipple pain or soreness': 'Ensure proper latch and positioning, use lanolin cream or hydrogel pads, seek help from a lactation consultant if needed',
  'plugged milk duct': 'Continue breastfeeding or pumping frequently, apply heat and massage to the affected area, ensure proper latch and positioning',
  'thrush': 'Treat both mother and baby simultaneously, take prescribed antifungal medications, practice good hygiene',
  'gastroesophageal reflux (GER)': 'Feed smaller, more frequent meals, hold baby upright after feedings, avoid tight diapers or clothing around the abdomen',
  'colic': 'Try soothing techniques (swaddling, gentle rocking), ensure proper burping after feedings, consult healthcare professionals if crying persists',
  'diaper rash': 'Change diapers frequently, apply barrier creams or ointments, give diaper-free time',
  'eczema': 'Use mild, fragrance-free skincare products, moisturize regularly, avoid triggers like harsh soaps and fabrics',
  'food allergies': 'Avoid allergenic foods, read labels carefully, carry emergency medication (epinephrine auto-injector if applicable)',
  'respiratory allergies': 'Limit exposure to allergens (pollen, dust mites, pet dander), use air purifiers or filters, take prescribed antihistamines',
  'contact dermatitis': 'Identify and avoid triggers (irritants or allergens), use mild, fragrance-free skincare products, apply corticosteroid creams or ointments',
  'heat rash': 'Keep affected area cool and dry, wear loose-fitting clothing, apply calamine lotion or hydrocortisone cream',
  'diaper rash': 'Change diapers frequently, apply barrier creams or ointments, give diaper-free time',
  'cradle cap': 'Gently wash affected area with mild baby shampoo, use a soft brush to loosen scales, apply moisturizer or oil after washing',
  'oral thrush': 'Use prescribed antifungal medications (nystatin), sterilize pacifiers and bottles regularly, practice good oral hygiene',
  'baby acne': 'Gently wash affected area with mild baby soap and water, avoid using oily or fragranced products, avoid picking or squeezing lesions',
  'milk protein allergy': 'Eliminate dairy products from diet (breastfeeding mother or formula-fed baby), use hypoallergenic formula if needed, monitor for improvement',
  'lactose intolerance': 'Avoid lactose-containing foods (dairy products), use lactose-free or lactose-reduced products if needed, take lactase enzyme supplements',
  'constipation': 'Ensure adequate fluid intake (for breastfeeding mother or formula-fed baby), offer high-fiber foods (for older infants), gently massage baby\'s belly',
  'gastroesophageal reflux (GER)': 'Feed smaller, more frequent meals, hold baby upright after feedings, burp baby frequently',
  'colic': 'Try soothing techniques (swaddling, gentle rocking), give baby a pacifier, ensure a calm environment',
  'ear infection': 'Take prescribed antibiotics, use over-the-counter pain relievers for pain relief, apply warm compresses to the ear',
  'bronchiolitis': 'Ensure hydration, use a cool-mist humidifier, monitor for signs of respiratory distress',
  'croup': 'Use a cool-mist humidifier, offer fluids to prevent dehydration, keep baby calm and comforted',
  'hand, foot, and mouth disease': 'Offer cold fluids and soft foods, use over-the-counter pain relievers for pain relief, maintain good hygiene to prevent spread of infection',
  'rotavirus': 'Ensure hydration with oral rehydration solution (ORS), offer small, frequent feedings, monitor for signs of dehydration',
  'respiratory syncytial virus (RSV)': 'Ensure hydration, use a cool-mist humidifier, monitor for signs of respiratory distress',
  'chickenpox': 'Apply calamine lotion to soothe itching, use over-the-counter antihistamines for itch relief, avoid scratching to prevent infection',
  'measles': 'Get plenty of rest, use over-the-counter pain relievers for fever and discomfort, use a humidifier to ease cough and congestion',
  'mumps': 'Get plenty of rest, use over-the-counter pain relievers for fever and discomfort, apply warm or cold compresses to swollen glands',
  'rubella': 'Get plenty of rest, use over-the-counter pain relievers for fever and discomfort, apply cool compresses to reduce rash',
  'polio': 'Get vaccinated, practice good hygiene, avoid close contact with infected individuals',
  'hepatitis': 'Get vaccinated (if applicable), practice good hygiene, avoid sharing needles or engaging in risky behaviors',
  'HIV/AIDS': 'Take antiretroviral medications as prescribed, practice safe sex, avoid sharing needles',
  'influenza': 'Get vaccinated annually, rest, drink fluids, use over-the-counter medications for symptom relief',
  'common cold': 'Get plenty of rest, stay hydrated, use over-the-counter medications for symptom relief',
  'norovirus': 'Stay hydrated, rest, practice good hygiene to prevent spread of infection',
  'Lyme disease': 'Take prescribed antibiotics, use insect repellent, perform tick checks after outdoor activities',
  'pneumococcal disease': 'Get vaccinated, practice good hygiene, avoid close contact with sick individuals',
  'tuberculosis': 'Take prescribed antibiotics for the full course, practice good respiratory hygiene, get tested if exposed to someone with TB',
  'streptococcal infection': 'Take prescribed antibiotics for the full course, practice good hygiene, avoid close contact with sick individuals',
  'salmonella infection': 'Stay hydrated, rest, avoid foods that may be contaminated, practice good hygiene',
  'shingles': 'Take antiviral medications as prescribed, use over-the-counter pain relievers, apply cool compresses to affected areas',
  'sepsis': 'Seek medical help immediately, receive intravenous antibiotics, manage symptoms in intensive care',
  'severe acute respiratory syndrome (SARS)': 'Seek medical help immediately, practice good hygiene, avoid close contact with sick individuals',
  'malaria': 'Take prescribed antimalarial medications, use insect repellent, sleep under insecticide-treated bed nets',
  'west Nile virus': 'Use insect repellent, wear long sleeves and pants, avoid outdoor activities during peak mosquito times',
  'avian influenza': 'Avoid contact with sick birds or poultry, cook poultry thoroughly before eating, get vaccinated (if applicable)',
  'swine flu': 'Get vaccinated annually, practice good hygiene, avoid close contact with sick individuals',
  'Middle East respiratory syndrome (MERS)': 'Seek medical help immediately, practice good hygiene, avoid contact with camels or their bodily fluids',
  'coronavirus disease (COVID-19)': 'Wear masks, practice social distancing, get vaccinated',
  'rotavirus': 'Ensure hydration with oral rehydration solution (ORS), continue breastfeeding or formula feeding, practice good hygiene',
  'Ebola virus disease': 'Seek medical help immediately, practice good hygiene, avoid contact with bodily fluids of sick individuals',
  'Marburg virus disease': 'Seek medical help immediately, practice good hygiene, avoid contact with bats or their bodily fluids',
  'severe acute respiratory syndrome (SARS)': 'Seek medical help immediately, practice good hygiene, avoid close contact with sick individuals',
  'cholera': 'Drink oral rehydration solution (ORS), seek medical help, practice good hygiene to prevent spread of infection',
  'liver disease': 'Follow prescribed treatment, avoid alcohol and drugs, maintain a healthy diet',
  'kidney disease': 'Follow prescribed treatment, manage blood pressure and blood sugar levels, maintain a healthy diet',
  'heart disease': 'Follow prescribed treatment, maintain a healthy diet, exercise regularly',
  'stroke': 'Seek immediate medical help, follow prescribed treatment, attend rehabilitation',
  'asthma': 'Use inhaler as prescribed, avoid triggers, monitor symptoms',
  'chronic obstructive pulmonary disease (COPD)': 'Use prescribed medications, avoid smoke and pollutants, exercise regularly',
  'diabetes': 'Monitor blood sugar levels, follow prescribed treatment, maintain a healthy lifestyle',
  'cancer': 'Undergo prescribed treatments, manage symptoms, seek support from healthcare professionals and support groups',
  'Alzheimer\'s disease': 'Follow prescribed treatment, maintain a supportive environment, seek caregiver support',
  'Parkinson\'s disease': 'Take prescribed medications, attend physical therapy, maintain a healthy lifestyle',
  'arthritis': 'Stay active, use pain relievers, attend physical therapy',
  'osteoporosis': 'Take prescribed medications, consume calcium and vitamin D, engage in weight-bearing exercise',
  'fibromyalgia': 'Get regular exercise, practice relaxation techniques, maintain a regular sleep schedule',
  'multiple sclerosis': 'Take prescribed medications, attend physical therapy, maintain a healthy lifestyle',
  'Crohn\'s disease': 'Follow prescribed treatment, maintain a healthy diet, manage stress',
  'ulcerative colitis': 'Follow prescribed treatment, maintain a healthy diet, manage stress',
  'irritable bowel syndrome (IBS)': 'Identify triggers, manage stress, follow a low-FODMAP diet',
  'celiac disease': 'Follow a gluten-free diet, manage symptoms with medication if needed',
  'hypothyroidism': 'Take thyroid hormone replacement medication, maintain a healthy diet, exercise regularly',
  'hyperthyroidism': 'Take prescribed medications, avoid caffeine and iodine-rich foods, manage stress',
  'anemia': 'Take iron supplements, eat foods rich in iron and vitamin C, manage underlying cause',
  'vitamin deficiency': 'Take vitamin supplements, eat a balanced diet, manage underlying cause',
  'hypertension': 'Follow a low-sodium diet, exercise regularly, manage stress',
  'hypotension': 'Increase fluid and salt intake, wear compression stockings, avoid prolonged standing',
  'high cholesterol': 'Follow a low-fat diet, exercise regularly, take prescribed medications',
  'diarrhea': 'Stay hydrated, eat bland foods, take anti-diarrheal medications if needed',
  'constipation': 'Eat foods high in fiber, drink plenty of water, exercise regularly',
  'gastroesophageal reflux disease (GERD)': 'Avoid trigger foods, eat smaller meals, elevate the head of the bed',
  'peptic ulcer disease': 'Avoid trigger foods, take prescribed medications, eat regular meals',
  'gallstones': 'Eat a low-fat diet, avoid rapid weight loss, manage symptoms with medication if needed',
  'liver cirrhosis': 'Avoid alcohol, follow a low-sodium diet, take prescribed medications',
  'hepatitis': 'Get vaccinated, practice good hygiene, avoid sharing needles',
  'pancreatitis': 'Avoid alcohol and fatty foods, follow prescribed treatment, manage symptoms with medication',
  'diverticulitis': 'Eat a high-fiber diet, avoid seeds and nuts, take prescribed antibiotics if needed',
  'hemorrhoids': 'Eat high-fiber foods, drink plenty of water, use over-the-counter treatments for pain and itching',
  'food allergies': 'Avoid trigger foods, read labels carefully, carry emergency medication (epinephrine auto-injector if applicable)',
  'lactose intolerance': 'Avoid dairy products, use lactase supplements if needed, consume lactose-free dairy alternatives',
  'sleep apnea': 'Use a CPAP machine, lose weight if needed, avoid alcohol and sedatives before bedtime',
  'insomnia': 'Establish a bedtime routine, limit caffeine and screen time before bed, practice relaxation techniques',
  'restless legs syndrome': 'Take prescribed medications, practice good sleep hygiene, exercise regularly',
  'TMJ disorder': 'Apply heat or cold packs, avoid hard or chewy foods, practice relaxation techniques',
  'trigeminal neuralgia': 'Take prescribed medications, avoid triggers, maintain good oral hygiene',
  'myofascial pain syndrome': 'Apply heat or cold packs, practice relaxation techniques, perform gentle stretching exercises',
  'temporomandibular joint dysfunction (TMD)': 'Apply moist heat or cold packs, avoid hard or chewy foods, practice relaxation techniques',
  'plantar fasciitis': 'Rest the foot, apply ice, perform stretching exercises, wear supportive shoes',
  'Achilles tendinitis': 'Rest the foot, apply ice, perform stretching exercises, wear supportive shoes',
  'shin splints': 'Rest the leg, apply ice, perform stretching exercises, wear supportive shoes',
  'patellar tendinitis': 'Rest the knee, apply ice, perform stretching exercises, wear a knee brace',
  'tennis elbow': 'Rest the arm, apply ice, perform stretching and strengthening exercises',
  'golfer\'s elbow': 'Rest the arm, apply ice, perform stretching and strengthening exercises',
  'carpal tunnel syndrome': 'Rest the wrist, apply ice, wear a wrist splint, perform stretching exercises',
  'sciatica': 'Apply hot or cold packs, perform stretching exercises, take over-the-counter pain relievers',
  'herniated disc': 'Rest, apply ice or heat, take over-the-counter pain relievers, perform gentle exercises',
  'whiplash': 'Apply ice or heat, take over-the-counter pain relievers, perform gentle neck exercises',
  'rotator cuff injury': 'Rest the shoulder, apply ice or heat, perform stretching and strengthening exercises',
  'frozen shoulder': 'Apply ice or heat, perform stretching and strengthening exercises, seek physical therapy',
  'osteoarthritis': 'Exercise regularly, apply heat or cold packs, take over-the-counter pain relievers',
  'rheumatoid arthritis': 'Take prescribed medications, exercise regularly, apply heat or cold packs',
  'gout': 'Avoid trigger foods, take prescribed medications, stay hydrated',
  'ankylosing spondylitis': 'Exercise regularly, take prescribed medications, maintain good posture',
  'fibromyalgia': 'Get regular exercise, practice relaxation techniques, maintain a regular sleep schedule',
  'chronic fatigue syndrome': 'Practice pacing and activity management, get restorative sleep, seek support from healthcare professionals',
  'endometriosis': 'Take prescribed medications, practice heat therapy, consider surgical intervention if needed',
  'polycystic ovary syndrome (PCOS)': 'Maintain a healthy diet, exercise regularly, manage symptoms with hormonal therapies if needed',
  'pelvic inflammatory disease (PID)': 'Take prescribed antibiotics, rest, avoid sexual activity until treatment is completed',
  'premenstrual syndrome (PMS)': 'Exercise regularly, eat a balanced diet, practice stress management techniques',
  'vaginal yeast infection': 'Take antifungal medications, practice good hygiene, avoid irritants like scented products',
  'bacterial vaginosis': 'Take prescribed antibiotics, practice good hygiene, avoid irritants like scented products',
  'urinary tract infection (UTI)': 'Take prescribed antibiotics, drink plenty of water, avoid',
    'stomachache': 'Antacid, Dicyclomine',
    'stomach ache': 'Antacid, Dicyclomine',
    'constipation': 'Ensure adequate fluid intake, offer high-fiber foods (prunes, pears), gently massage baby\'s belly',
    'gastroesophageal reflux (GER)': 'Feed smaller, more frequent meals, hold baby upright after feedings, burp baby frequently',
    'colic': 'Try soothing techniques (swaddling, white noise), give baby a pacifier, ensure a calm environment',
    'ear infection': 'Take prescribed antibiotics, use over-the-counter pain relievers for pain relief, apply warm compresses to the ear',
    'bronchiolitis': 'Ensure hydration, use a cool-mist humidifier, monitor for signs of respiratory distress',
    'croup': 'Use a cool-mist humidifier, offer fluids to prevent dehydration, keep baby calm and comforted',
    'hand, foot, and mouth disease': 'Offer cold fluids and soft foods, use over-the-counter pain relievers for pain relief, maintain good hygiene to prevent spread of infection',
    'rotavirus': 'Ensure hydration with oral rehydration solution, offer small, frequent feedings, monitor for signs of dehydration',
    'respiratory syncytial virus (RSV)': 'Ensure hydration, use a cool-mist humidifier, monitor for signs of respiratory distress',
    'chickenpox': 'Apply calamine lotion to soothe itching, use over-the-counter antihistamines for itch relief, avoid scratching to prevent infection',
    'polio': 'Get vaccinated, practice good hygiene, avoid close contact with infected individuals',
    'hepatitis': 'Get vaccinated (if applicable), practice good hygiene, avoid sharing needles or engaging in risky behaviors',
    'HIV/AIDS': 'Take antiretroviral medications as prescribed, practice safe sex, avoid sharing needles',
    'influenza': 'Get vaccinated annually, rest, drink fluids, use over-the-counter medications for symptom relief',
    'common cold': 'Get plenty of rest, stay hydrated, use over-the-counter medications for symptom relief',
    'norovirus': 'Stay hydrated, rest, practice good hygiene to prevent spread of infection',
    'Lyme disease': 'Take prescribed antibiotics, use insect repellent, perform tick checks after outdoor activities',
    'pneumococcal disease': 'Get vaccinated, practice good hygiene, avoid close contact with sick individuals',
    'tuberculosis': 'Take prescribed antibiotics for the full course, practice good respiratory hygiene, get tested if exposed to someone with TB',
    'streptococcal infection': 'Take prescribed antibiotics for the full course, practice good hygiene, avoid close contact with sick individuals',
    'salmonella infection': 'Stay hydrated, rest, avoid foods that may be contaminated, practice good hygiene',
    'shingles': 'Take antiviral medications as prescribed, use over-the-counter pain relievers, apply cool compresses to affected areas',
    'sepsis': 'Seek medical help immediately, receive intravenous antibiotics, manage symptoms in intensive care',
    'severe acute respiratory syndrome (SARS)': 'Seek medical help immediately, practice good hygiene, avoid close contact with sick individuals',
    'malaria': 'Take prescribed antimalarial medications, use insect repellent, sleep under insecticide-treated bed nets',
    'west Nile virus': 'Use insect repellent, wear long sleeves and pants, avoid outdoor activities during peak mosquito times',
    'avian influenza': 'Avoid contact with sick birds or poultry, cook poultry thoroughly before eating, get vaccinated (if applicable)',
    'swine flu': 'Get vaccinated annually, practice good hygiene, avoid close contact with sick individuals',
    'Middle East respiratory syndrome (MERS)': 'Seek medical help immediately, practice good hygiene, avoid contact with camels or their bodily fluids',
    'coronavirus disease (COVID-19)': 'Wear masks, practice social distancing, get vaccinated',
    'rotavirus': 'Ensure hydration with oral rehydration solution, continue breastfeeding or formula feeding, practice good hygiene',
    'Ebola virus disease': 'Seek medical help immediately, practice good hygiene, avoid contact with bodily fluids of sick individuals',
    'Marburg virus disease': 'Seek medical help immediately, practice good hygiene, avoid contact with bats or their bodily fluids',
    'cholera': 'Drink oral rehydration solution, seek medical help, practice good hygiene to prevent spread of infection',
    'liver disease': 'Follow prescribed treatment, avoid alcohol and drugs, maintain a healthy diet',
    'kidney disease': 'Follow prescribed treatment, manage blood pressure and blood sugar levels, maintain a healthy diet',
    'heart disease': 'Follow prescribed treatment, maintain a healthy diet, exercise regularly',
    'stroke': 'Seek immediate medical help, follow prescribed treatment, attend rehabilitation',
    'asthma': 'Use inhaler as prescribed, avoid triggers, monitor symptoms',
    'chronic obstructive pulmonary disease (COPD)': 'Use prescribed medications, avoid smoke and pollutants, exercise regularly',
    'thyroid': 'Levothyroxine',
    'jaundice' : 'Antihistamines, Cholestyramine, Rifampin, and Naltrexone.',
    'blood pressure' : 'Follow a low-sodium diet, exercise regularly, manage stress',
    'marasmus': 'Nutritional rehabilitation, high-calorie diet, and treatment of underlying medical conditions.',
  'kwashiorkor': 'Nutritional rehabilitation, high-protein diet, and treatment of underlying medical conditions.',
  'tetanus': 'Tetanus toxoid vaccination, wound care, and administration of tetanus immune globulin.',
  'elephantiasis': 'Medication to kill the parasitic worms, such as albendazole, ivermectin, or diethylcarbamazine (DEC).',
  'goitre': 'Iodine supplements, thyroid hormone replacement therapy, or surgery.',
  'rickets': 'Vitamin D supplements, calcium supplements, and sunlight exposure.',
  'scurvy': 'Vitamin C supplements and consumption of vitamin C-rich foods such as citrus fruits.',
  'night blindness': 'Vitamin A supplements and consumption of vitamin A-rich foods such as carrots and leafy greens.',
  'viral fever': 'Antipyretic medications, rest, and hydration.',
  'smallpox': 'Smallpox vaccination and supportive care for symptoms.',
  'sedentary': 'Regular physical activity and lifestyle modifications.',
  'vitiligo': 'Topical corticosteroids, phototherapy, and depigmentation therapy.',
  'cataract': 'Cataract surgery to remove the cloudy lens and replace it with an artificial lens.',
  'kidney stone': 'Pain medications, increased fluid intake, and dietary changes to prevent stone formation.',
  'cervical': 'Treatment depends on the underlying cause, ranging from physical therapy to surgery.',
  'tonsils': 'Antibiotics, tonsillectomy (surgical removal of the tonsils), and supportive care.',
  'tonsillitis': 'Antibiotics, pain relievers, and supportive care such as rest and hydration.',
  'hay fever': 'Antihistamines, nasal corticosteroids, and allergy shots (immunotherapy).',
  'beriberi': 'Thiamine (vitamin B1) supplements and dietary changes.',
  'heatstroke': 'Cooling measures such as moving to a shaded or air-conditioned area, hydration, and medical attention.',
  'breast cancer': 'Surgery, chemotherapy, radiation therapy, hormone therapy, and targeted therapy.',
  'leukemia': 'Chemotherapy, radiation therapy, stem cell transplant, and targeted therapy.',
  'haemophilia': 'Clotting factor replacement therapy, medications, and supportive care.',
  'thalassemia': 'Blood transfusions, iron chelation therapy, and bone marrow transplant.',
  'drying of cornea': 'Eye lubricants, artificial tears, and treatment of underlying conditions such as dry eye syndrome.',
  'pellagra': 'Niacin (vitamin B3) supplements and dietary changes.',
  'dermatitis': 'Topical corticosteroids, antihistamines, and avoiding triggers.',
  'anaemia': 'Iron supplements, vitamin supplements, and treatment of underlying causes.',
  'dysentery': 'Antibiotics, antiparasitic medications, hydration, and electrolyte replacement.',
  'sinus': 'Nasal decongestants, saline nasal irrigation, and corticosteroid nasal sprays.',
  'pimple': 'Topical treatments such as benzoyl peroxide, salicylic acid, and retinoids.',
  'blackhead': 'Topical treatments, such as salicylic acid and retinoids, and manual extraction.',
  'bird flu': 'Antiviral medications, supportive care, and prevention measures such as vaccination.',
  'coronavirus': 'Prevention measures such as vaccination, wearing masks, and practicing good hygiene.',
  'e.coli': 'Hydration, rest, and sometimes antibiotics.',
  'oedema': 'Diuretics, dietary changes, and treatment of underlying conditions.',
  'pcod': 'Lifestyle modifications, weight management, hormone therapy, and fertility treatments as needed.',
  'plague': 'Antibiotics, Oxygen therapy, Intravenous fluids.',
  'aids': 'Antiretroviral therapy (ART), Pre-exposure prophylaxis (PrEP).',
  'sleeping sickness': 'Suramin, Pentamidine, Eflornithine, Melarsoprol.',
  'ascariasis': 'Anthelmintic medications like Albendazole, Mebendazole.',
  'taeniasis': 'Praziquantel, Niclosamide.',
  'diphtheria': 'Antibiotics like Penicillin or Erythromycin, Antitoxin.',
  'gonorrhoea': 'Antibiotics like Ceftriaxone and Azithromycin.',
  'poliomyelitis': 'Vaccine (Inactivated poliovirus vaccine or Oral poliovirus vaccine).',
  'measles': 'Vitamin A supplements, Supportive care to manage symptoms.',
  'leprosy': 'Multidrug therapy (MDT) with Rifampicin, Dapsone, and Clofazimine.',
  'syphilis': 'Antibiotics like Penicillin.',
  'amoebiasis': 'Antibiotics like Metronidazole or Tinidazole.',
  'filariasis': 'Diethylcarbamazine (DEC), Ivermectin, Albendazole.',
  'coronavirus': 'Supportive care, Oxygen therapy, Antiviral medications like Remdesivir, Dexamethasone for severe cases.',
  'corona virus': 'Supportive care, Oxygen therapy, Antiviral medications like Remdesivir, Dexamethasone for severe cases.',
  'conjunctivitis': 'Artificial tears, Antibiotic eye drops for bacterial conjunctivitis, Antihistamine eye drops for allergic conjunctivitis.',
  'low sugar': 'Consume glucose tablets, Drink fruit juice or regular soda, Eat small snacks with carbohydrates like crackers or fruit.',
  'high sugar': 'Insulin therapy, Oral diabetes medications like metformin, Lifestyle changes (diet, exercise), Monitoring blood sugar levels regularly.',
  'leptospirosis': 'Antibiotics like doxycycline, Penicillin, Supportive care including hydration and rest, Hospitalization for severe cases.',
  'chlamydia': 'Antibiotics like azithromycin or doxycycline, Treatment for sexual partners, Abstain from sexual activity during treatment.',
  'gastroenteritis': 'Oral rehydration solution (ORS), Intravenous fluids for severe dehydration, Antiemetics for nausea and vomiting, Antibiotics for bacterial gastroenteritis if indicated.',
  'hiv': 'Antiretroviral therapy (ART), Pre-exposure prophylaxis (PrEP) for prevention, Post-exposure prophylaxis (PEP) for recent exposures, Supportive care and treatment of opportunistic infections.',
  'sars': 'Supportive care including oxygen therapy, Antiviral medications like ribavirin, Corticosteroids for severe cases, Isolation to prevent spread.',
  'cellulitis': 'Antibiotics like dicloxacillin, cephalexin, or clindamycin, Wound care and elevation of affected area, Pain management, Hospitalization for severe cases.',
  'cirrhosis': 'Management of complications (ascites, hepatic encephalopathy, etc.), Alcohol cessation if applicable, Dietary changes (low sodium diet), Liver transplant in severe cases.',
  'giardiasis': 'Antibiotics like metronidazole or tinidazole, Hydration therapy for dehydration, Proper hygiene and sanitation to prevent transmission, Treatment for close contacts if necessary.'


  };
  // Initialize an empty array to store suggested medicines
  const suggestedMedicines = [];
  
  // Iterate through the symptoms and suggest corresponding medicines
  symptoms.forEach(symptom => {
    if (medicineMapping.hasOwnProperty(symptom)) {
      suggestedMedicines.push(medicineMapping[symptom]);
    }
  });
  
  // Display the suggested medicines or indicate no information available
  const suggestionElement = document.getElementById('medicineSuggestion');
  if (suggestedMedicines.length > 0) {
    suggestionElement.textContent = "Suggested cures: " + suggestedMedicines.join(', ');
  } else {
    suggestionElement.textContent = "No information available for the given symptoms.";
  }
  
  